-- Generated by DragonwildsAssets (scripts/blender/compose/compose_overlay.py (brassitato.json, v003, seed 4)); edit the recipe, not this file.
-- Units: UE cm, FRotator degrees {Pitch, Yaw, Roll}, relative to the host mesh pivot.
return {
  schema = "ess.hybrid_placement/1",
  generator = "scripts/blender/compose/compose_overlay.py (brassitato.json, v003, seed 4)",
  hybrid_id = "hort_plant_brassitato",
  display_name = "Brassitato",
  version = "v003",
  units = {
    location = "cm",
    rotation = "degrees FRotator [Pitch, Yaw, Roll]",
    scale = "multiplier",
    space = "relative to the host mesh pivot; attach to the host's plot PlantMeshComponent (the cabbage stage mesh)",
  },
  usage = "shape = shapes[hosts[<host StaticMesh path>]]; for each attachment spawn a StaticMeshComponent with mesh, attach to the host component with the relative transform",
  groups = {
    nestled = "vanilla cabbage heads resting in the potato plant's leaves",
    heart = "one cabbage head crowning the plant",
  },
  component_defaults = {
    collision = "NoCollision",
    cast_shadow = true,
    cull_distance_cm = 4000,
  },
  meshes = {
    ["/Game/Art/Item/Resources/Cabbage/SM_Cabbage_01v3"] = {
      owner = "vanilla",
      material = "/Game/Art/Item/Resources/Cabbage/Materials/MI_Cabbage_01",
    },
  },
  hosts = {
    ["/Game/Art/Item/Resources/Potato/SM_Potato_Plant_01"] = "shape_1",
    ["/Game/Art/Item/Resources/Potato/SM_Potato_Plant_01v2"] = "shape_2",
    ["/Game/Art/Item/Resources/Potato/SM_Potato_Plant_01v3"] = "shape_3",
  },
  shapes = {
    shape_1 = {
      hash = "9c43c2f875fb",
      authored_on = "/Game/Art/Item/Resources/Potato/SM_Potato_Plant_01",
      vertices = 758,
      attachments = {
        {
          name = "piece_ring_0",
          mesh = "/Game/Art/Item/Resources/Cabbage/SM_Cabbage_01v3",
          location = {-11.09, 2.32, 60.88},
          rotation = {-0.3, 325.98, -8.68},
          scale = {0.9006, 0.9006, 0.9006},
          group = "nestled",
          requires_pak = false,
        },
        {
          name = "piece_heart_0",
          mesh = "/Game/Art/Item/Resources/Cabbage/SM_Cabbage_01v3",
          location = {1.18, 3.82, 54.13},
          rotation = {0.43, 91.49, 65.84},
          scale = {1.0, 1.0, 1.0},
          group = "heart",
          requires_pak = false,
        },
      },
      width_cm = 69.3,
      height_cm = 164.4,
    },
    shape_2 = {
      hash = "bab550e8fee5",
      authored_on = "/Game/Art/Item/Resources/Potato/SM_Potato_Plant_01v2",
      vertices = 164,
      attachments = {
        {
          name = "piece_ring_0",
          mesh = "/Game/Art/Item/Resources/Cabbage/SM_Cabbage_01v3",
          location = {-19.13, -4.39, -10.74},
          rotation = {-6.54, 97.15, -5.36},
          scale = {0.6615, 0.6615, 0.6615},
          group = "nestled",
          requires_pak = false,
        },
        {
          name = "piece_heart_0",
          mesh = "/Game/Art/Item/Resources/Cabbage/SM_Cabbage_01v3",
          location = {-7.79, -0.65, 15.05},
          rotation = {7.87, 51.88, 60.22},
          scale = {0.7721, 0.7721, 0.7721},
          group = "heart",
          requires_pak = false,
        },
      },
      width_cm = 45.6,
      height_cm = 60.6,
    },
    shape_3 = {
      hash = "cd03de7ec626",
      authored_on = "/Game/Art/Item/Resources/Potato/SM_Potato_Plant_01v3",
      vertices = 218,
      attachments = {
        {
          name = "piece_ring_0",
          mesh = "/Game/Art/Item/Resources/Cabbage/SM_Cabbage_01v3",
          location = {-20.02, 13.51, 29.91},
          rotation = {-11.12, 81.28, -13.07},
          scale = {0.9793, 0.9793, 0.9793},
          group = "nestled",
          requires_pak = false,
        },
        {
          name = "piece_heart_0",
          mesh = "/Game/Art/Item/Resources/Cabbage/SM_Cabbage_01v3",
          location = {-8.13, 6.63, 21.99},
          rotation = {-5.13, 353.8, 60.02},
          scale = {1.0, 1.0, 1.0},
          group = "heart",
          requires_pak = false,
        },
      },
      width_cm = 64.4,
      height_cm = 94.5,
    },
  },
}
