-- Generated by DragonwildsAssets (scripts/blender/compose/compose_overlay.py (weeping_oak.json, v003, seed 8)); edit the recipe, not this file.
-- Units: UE cm, FRotator degrees {Pitch, Yaw, Roll}, relative to the host mesh pivot.
return {
  schema = "ess.hybrid_placement/1",
  generator = "scripts/blender/compose/compose_overlay.py (weeping_oak.json, v003, seed 8)",
  hybrid_id = "hort_plant_weeping_oak",
  display_name = "Weeping Oak",
  version = "v003",
  units = {
    location = "cm",
    rotation = "degrees FRotator [Pitch, Yaw, Roll]",
    scale = "multiplier",
    space = "relative to the host mesh pivot; attach to the host's RootStaticMeshComponent",
  },
  usage = "shape = shapes[hosts[<host StaticMesh path>]]; for each attachment spawn a StaticMeshComponent with mesh, attach to the host component with the relative transform",
  groups = {
    overlay = "vanilla willow canopy hung inside the oak crown; its fronds are the drooping branches (apply material_overrides)",
  },
  component_defaults = {
    collision = "NoCollision",
    cast_shadow = true,
    cull_distance_cm = 15000,
  },
  meshes = {
    ["/Game/Art/Env/Landscape/Foliage/Trees/Willow/Willow_01_Components/SM_Willow_01_Canopy"] = {
      owner = "vanilla",
      material = "mesh default (MI_FH_Willow_Leaves), recoloured per material_overrides",
    },
  },
  hosts = {
    ["/Game/Art/Env/Landscape/Foliage/Trees/Oak_Tree/SM_BM_Oak_Tree_01"] = "shape_1",
    ["/Game/Art/Env/Landscape/Foliage/Trees/Oak_Tree/SM_BM_Oak_Tree_02"] = "shape_2",
    ["/Game/Art/Env/Landscape/Foliage/Trees/Oak_Tree/SM_FH_Oak_Tree_01"] = "shape_1",
    ["/Game/Art/Env/Landscape/Foliage/Trees/Oak_Tree/SM_FH_Oak_Tree_02"] = "shape_2",
    ["/Game/Art/Env/Landscape/Foliage/Trees/Oak_Tree/SM_GF_Oak_Tree_01"] = "shape_1",
    ["/Game/Art/Env/Landscape/Foliage/Trees/Oak_Tree/SM_GF_Oak_Tree_02"] = "shape_2",
  },
  shapes = {
    shape_1 = {
      hash = "f9d101566830",
      authored_on = "/Game/Art/Env/Landscape/Foliage/Trees/Oak_Tree/SM_BM_Oak_Tree_01",
      vertices = 52815,
      attachments = {
        {
          name = "overlay_0",
          mesh = "/Game/Art/Env/Landscape/Foliage/Trees/Willow/Willow_01_Components/SM_Willow_01_Canopy",
          location = {-89.48, 71.15, 47.11},
          rotation = {0, 0, 0},
          scale = {0.7734, 0.7734, 0.7734},
          group = "overlay",
          requires_pak = false,
          material_overrides = {
            {
              slot = 0,
              base = "/Game/Art/Env/Landscape/Foliage/Trees/Materials/MI_FH_Willow_Leaves",
              parent = "/Game/Materials/Environment/M_Foliage_Tree",
              vector = {
                Color_Mult_A = {1.15, 1.45, 0.2, 1.0},
                Color_Mult_B = {1.15, 1.45, 0.2, 1.0},
              },
              scalar = {
                Color_Mult_Blend = 1.0,
                ["Subsurface Amount scale"] = 0.35,
              },
              defaults = {
                Color_Mult_A = {1, 1, 1, 1},
                Color_Mult_B = {1, 1, 1, 1},
                Color_Mult_Blend = 0,
                ["Subsurface Amount scale"] = 1,
              },
              preview_multiply_param = "Color_Mult_A",
              why = "linear multiplier taking the willow leaf texels (mean linear 0.045, 0.120, 0.221) to the green of the vanilla BM ash leaves (0.073, 0.186, 0.009), softened so highlights stay green; A and B both set and Blend 1 so the result is the same whichever way the graph blends them",
              verified = "names, types (vector/scalar) and defaults read from the cooked M_Foliage_Tree parameter table; the in-game look of the multiply is UNVERIFIED",
            },
          },
        },
      },
      canopy_cm = {
        z = {651, 1657},
        radius = 701,
      },
    },
    shape_2 = {
      hash = "26cbea85463b",
      authored_on = "/Game/Art/Env/Landscape/Foliage/Trees/Oak_Tree/SM_BM_Oak_Tree_02",
      vertices = 56313,
      attachments = {
        {
          name = "overlay_0",
          mesh = "/Game/Art/Env/Landscape/Foliage/Trees/Willow/Willow_01_Components/SM_Willow_01_Canopy",
          location = {-130.99, 103.3, -50.76},
          rotation = {0, 0, 0},
          scale = {1.0, 1.0, 1.0},
          group = "overlay",
          requires_pak = false,
          material_overrides = {
            {
              slot = 0,
              base = "/Game/Art/Env/Landscape/Foliage/Trees/Materials/MI_FH_Willow_Leaves",
              parent = "/Game/Materials/Environment/M_Foliage_Tree",
              vector = {
                Color_Mult_A = {1.15, 1.45, 0.2, 1.0},
                Color_Mult_B = {1.15, 1.45, 0.2, 1.0},
              },
              scalar = {
                Color_Mult_Blend = 1.0,
                ["Subsurface Amount scale"] = 0.35,
              },
              defaults = {
                Color_Mult_A = {1, 1, 1, 1},
                Color_Mult_B = {1, 1, 1, 1},
                Color_Mult_Blend = 0,
                ["Subsurface Amount scale"] = 1,
              },
              preview_multiply_param = "Color_Mult_A",
              why = "linear multiplier taking the willow leaf texels (mean linear 0.045, 0.120, 0.221) to the green of the vanilla BM ash leaves (0.073, 0.186, 0.009), softened so highlights stay green; A and B both set and Blend 1 so the result is the same whichever way the graph blends them",
              verified = "names, types (vector/scalar) and defaults read from the cooked M_Foliage_Tree parameter table; the in-game look of the multiply is UNVERIFIED",
            },
          },
        },
      },
      canopy_cm = {
        z = {773, 2010},
        radius = 930,
      },
    },
  },
  notes = "Apply each attachment's material_overrides: create a dynamic material instance on the attached component's slot (parent = the mesh's own material, MI_FH_Willow_Leaves) and set the listed vector and scalar parameters. Without it the fronds render cyan-blue (the vanilla willow look). SM_Willow_01_Canopy LOD0 is ~150k tris (vanilla LODs/impostor apply).",
}
