-- Generated by DragonwildsAssets (scripts/blender/compose/compose_overlay.py (weeping_oak.json, v001, seed 8)); edit the recipe, not this file.
-- Units: UE cm, FRotator degrees {Pitch, Yaw, Roll}, relative to the host mesh pivot.
return {
  schema = "ess.hybrid_placement/1",
  generator = "scripts/blender/compose/compose_overlay.py (weeping_oak.json, v001, seed 8)",
  hybrid_id = "hort_plant_weeping_oak",
  display_name = "Weeping Oak",
  version = "v001",
  units = {
    location = "cm",
    rotation = "degrees FRotator [Pitch, Yaw, Roll]",
    scale = "multiplier",
    space = "relative to the host mesh pivot; attach to the host's RootStaticMeshComponent",
  },
  usage = "shape = shapes[hosts[<host StaticMesh path>]]; for each attachment spawn a StaticMeshComponent with mesh, attach to the host component with the relative transform",
  groups = {
    overlay = "vanilla willow canopy hung inside the oak crown; its fronds are the drooping branches",
  },
  component_defaults = {
    collision = "NoCollision",
    cast_shadow = true,
    cull_distance_cm = 15000,
  },
  meshes = {
    ["/Game/Art/Env/Landscape/Foliage/Trees/Willow/Willow_01_Components/SM_Willow_01_Canopy"] = {
      owner = "vanilla",
      material = "mesh default (MI_FH_Willow_Leaves)",
    },
  },
  hosts = {
    ["/Game/Art/Env/Landscape/Foliage/Trees/Oak_Tree/SM_BM_Oak_Tree_01"] = "shape_1",
    ["/Game/Art/Env/Landscape/Foliage/Trees/Oak_Tree/SM_BM_Oak_Tree_02"] = "shape_2",
    ["/Game/Art/Env/Landscape/Foliage/Trees/Oak_Tree/SM_FH_Oak_Tree_01"] = "shape_1",
    ["/Game/Art/Env/Landscape/Foliage/Trees/Oak_Tree/SM_FH_Oak_Tree_02"] = "shape_2",
    ["/Game/Art/Env/Landscape/Foliage/Trees/Oak_Tree/SM_GF_Oak_Tree_01"] = "shape_1",
    ["/Game/Art/Env/Landscape/Foliage/Trees/Oak_Tree/SM_GF_Oak_Tree_02"] = "shape_2",
  },
  shapes = {
    shape_1 = {
      hash = "f9d101566830",
      authored_on = "/Game/Art/Env/Landscape/Foliage/Trees/Oak_Tree/SM_BM_Oak_Tree_01",
      vertices = 52815,
      attachments = {
        {
          name = "overlay_0",
          mesh = "/Game/Art/Env/Landscape/Foliage/Trees/Willow/Willow_01_Components/SM_Willow_01_Canopy",
          location = {-89.48, 71.15, 47.11},
          rotation = {0, 0, 0},
          scale = {0.7734, 0.7734, 0.7734},
          group = "overlay",
          requires_pak = false,
        },
      },
      canopy_cm = {
        z = {651, 1657},
        radius = 701,
      },
    },
    shape_2 = {
      hash = "26cbea85463b",
      authored_on = "/Game/Art/Env/Landscape/Foliage/Trees/Oak_Tree/SM_BM_Oak_Tree_02",
      vertices = 56313,
      attachments = {
        {
          name = "overlay_0",
          mesh = "/Game/Art/Env/Landscape/Foliage/Trees/Willow/Willow_01_Components/SM_Willow_01_Canopy",
          location = {-134.04, 106.5, -95.26},
          rotation = {0, 0, 0},
          scale = {1.0267, 1.0267, 1.0267},
          group = "overlay",
          requires_pak = false,
        },
      },
      canopy_cm = {
        z = {773, 2010},
        radius = 930,
      },
    },
  },
  notes = "Optional Lua tint: give the willow canopy's leaf material the oak leaf colour so the fronds read as oak. SM_Willow_01_Canopy LOD0 is ~150k tris (vanilla LODs/impostor apply).",
}
